s1 = set()
n1 = int(input("Enter a number: "))
s1.add(n1)
n2 = int(input("Enter a number: "))
s1.add(n2)
n3 = int(input("Enter a number: "))
s1.add(n3)
n4 = int(input("Enter a number: "))
s1.add(n4)
n5 = int(input("Enter a number: "))
s1.add(n5)
n6 = int(input("Enter a number: "))
s1.add(n6)
n7 = int(input("Enter a number: "))
s1.add(n7)
n8 = int(input("Enter a number: "))
s1.add(n8)
print(s1)